### ISSUE TITLE
offsetAndReplace.jsx

### ISSUE THREAD

**Issue by creold** [Tobl4/adobeIllustratorScripts#1]
Hi, Tobl.
I noticed in your script that after `app.executeMenuCommand("OffsetPath v23");` the old paths are removed anyway. But after all, the user could cancel the offset dialog. I suggest you first use a small function to compare if the selection has changed after the dialog and only if it's true do you remove the paths.

```
  redraw(); // Redraw screen after deselect
  app.executeMenuCommand("OffsetPath v23");

  // Remove old paths only if the dialog has not been cancelled
  if (!isEquals(oldSelect, selection)) {
    for (var i = oldSelect.length - 1; i >= 0; i--) {
      oldSelect[i].remove();
    }
  }
```

```
// Compare arrays
function isEquals(arr1, arr2) {
  if (arr1.length != arr2.length) return false;

  for (var i = 0; i < arr1.length; i++) {
    if (arr1[i] != arr2[i]) return false;
  }

  return true;
}
```
[update.jsx.zip](https://github.com/Tobl4/adobeIllustratorScripts/files/7060119/update.jsx.zip)

**Comment by Tobl4** [comment]
Thanks for the notice. I used it as an excuse to overhaul the selection handling from the ground up, check the new commit.
